routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MedicalRecordController;
use App\Http\Controllers\RatingController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::middleware(['role:admin'])->group(function () {

    Route::resource('users', UserController::class);

    Route::put('users/{user}/restore',
        [UserController::class, 'restore']
    )->name('users.restore');

    Route::delete('users/{user}/delete',
        [UserController::class, 'remove']
    )->name('users.remove');

    Route::get('/getData/{id}',
        [UserController::class, 'getData']);

});

Route::resource('roles', RoleController::class);

Route::get('/register', [RegisterController::class, 'index'])->name('register');
Route::post('/register',[RegisterController::class,'store'])->name('register.store');

Route::get('/login',[LoginController::class,'index'])->name('login');
Route::post('/login',[LoginController::class,'store']);
Route::get('/logout',[LoginController::class, 'logout'])->name('logout');

Route::middleware(['role:patient|doctor'])->group(function () {

    Route::get('/book',
        [BookingController::class, 'index'])
        ->name('book');

    Route::post('/book',
        [BookingController::class, 'store'])
        ->name('book.store');

    Route::get('/book/getData/{field}/{time}',
        [BookingController::class, 'getData']);

    Route::delete('/book/{id}',
        [BookingController::class, 'delete'])
        ->name('book.delete');
});

Route::middleware(['role:doctor|patient'])->group(function () {

    Route::get('/medical/records/{patient_id}',
        [MedicalRecordController::class, 'index'])
        ->name('medrecord');

    Route::post('medical/records/{patient_id}',
        [MedicalRecordController::class, 'store'])
        ->name('medrecord.store');
});

Route::middleware(['role:doctor'])->group(function () {

    Route::delete('medical/records/delete/{record_id}',
        [MedicalRecordController::class, 'delete'])
        ->name('medrecord.delete');
});

Route::middleware(['role:patient'])->group(function () {

    Route::post('/rate/{doctor_id}/{appointment_id}',
        [RatingController::class, 'store'])
        ->name('rate');
});

//Route::get('/calendar', [HomeController::class, 'calendar'])->name('calendar');

app/Models/User.php
<?php

namespace App\Models;

use App\Enums\RoleEnum;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'role_id',
        'field',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function ratings()
    {
        return $this->hasMany(Rating::class);
    }

    public function doctorAppointments()
    {
        return $this->hasMany(Appointment::class, 'doctor_id');
    }

    public function patientAppointments()
    {
        return $this->hasMany(Appointment::class, 'patient_id');
    }

    public function medicalRecords()
    {
        return $this->hasMany(MedicalRecord::class);
    }

    public function medicaments()
    {
        return $this->hasManyThrough(Medicament::class, MedicalRecord::class);
    }

    public function scopeDoctor($query)
    {
        return $query->whereHas('role', function ($q) {
            $q->where('slug', RoleEnum::DOCTOR);
        });
    }

    public function scopePatient($query)
    {
        return $query->whereHas('role', function ($q) {
            $q->where('slug', RoleEnum::PATIENT);
        });
    }

    public function hasRole($role)
    {
        return $this->role()->first()->slug == $role;
    }

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/Http/Controllers/Api/V1/UserController.php
<?php

namespace App\Http\Controllers\Api\V1;

use App\Http\Controllers\Controller;
use App\Http\Requests\StoreUserRequest;
use App\Http\Resources\UserResource;
use App\Http\Services\UserService;
use App\Models\User;
use App\Repositories\Contracts\UserRepositoryContract;
use Illuminate\Http\Request;

class UserController extends Controller
{
    private $userRepository;

    public function __construct(UserRepositoryContract $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function index()
    {
        return UserResource::collection(User::all());
    }

    public function store(StoreUserRequest $request)
    {
        $response = UserService::store($request->validated());
        if($response)
        {
            return response()->json(['message' => 'User created'], 200);
        } else return response()->json(['message' => 'Exception Error'], 400);
    }

    public function destroy(int $id)
    {
        $user = $this->userRepository->findUserByID($id);
        if ( !$user->trashed() )
            $user->delete();
        return response()->json(['message' => 'User deleted'], 200);
    }

    public function update(StoreUserRequest $request, $id)
    {
        $response = UserService::update($id, $request->validated());
        if ($response)
        {
            return response()->json(['message' => 'User edited'], 200);
        } else return response()->json(['message' => 'Exception Error'], 400);
    }

    public function restore($id)
    {
        $this->userRepository->findUserByID($id)->restore();
        return response()->json(['message' => 'User restored'], 200);
    }

    public function remove($id)
    {
        $this->userRepository->findUserByID($id)->forceDelete();
        return response()->json(['message' => 'User removed'], 200);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\UsersDataTable;
use App\Http\Requests\StoreUserRequest;
use App\Models\Role;
use App\Repositories\Contracts\UserRepositoryContract;
use App\Http\Services\UserService;
use Illuminate\Http\Request;
use App\Models\User;

class UserController extends Controller
{
    private $userRepository;

    public function __construct(UserRepositoryContract $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function index(Request $request, UsersDataTable $dataTable)
    {
        $roles = Role::pluck('name', 'id');

        return $dataTable->render('users.index', compact('roles'));
    }

    public function store(StoreUserRequest $request)
    {
        $response = UserService::store($request->validated());
        if($response)
        {
            return back();
        } else return response()->json(['message' => 'Exception Error'], 400);
    }

    public function destroy(int $id)
    {
        $user = $this->userRepository->findUserByID($id);
        if ( !$user->trashed() )
            $user->delete();
        return back();
    }

    public function update(StoreUserRequest $request, $id)
    {
        $response = UserService::update($id, $request->validated());
        if ($response)
        {
            return back();
        } else return response()->json(['message' => 'Exception Error'], 400);
    }

    public function restore($id)
    {
        $this->userRepository->findUserByID($id)->restore();
        return back();
    }

    public function remove($id)
    {
        $this->userRepository->findUserByID($id)->forceDelete();
        return back();
    }

    public function getData($id)
    {
        // get records from database
        $arr['data'] = User::where('id', $id)->first();

        return response()->json($arr,200);
    }
}

resources/views/users/action.blade.php
@if ( $deleted_at == null )
    @if(Auth::id() !== $id)
        <form action="{{ route('users.destroy', ['user' => $id]) }}" method="post" class="form">
            @csrf
            @method('DELETE')
            <div class="mb-1">
                <button type="submit" class="btn btn-sm btn-warning">
                    Block
                </button>
            </div>
        </form>
<!-- Button trigger Edit User -->
<button type="button" class="btn btn-sm btn-primary mb-1" onclick="editUser({{$id}})">
    Edit
</button>
    @endif
@else
<form action="{{ route('users.restore', ['user' => $id]) }}" method="post" class="form">
    @csrf
    @method('PUT')
    <div class="mb-1">
        <button type="submit" class="btn btn-sm btn-success">
            Restore
        </button>
    </div>
</form>
@endif
@if(Auth::id() !== $id)
    <form action="{{ route('users.remove', ['user' => $id]) }}" method="post" class="form">
        @csrf
        @method('DELETE')
        <div class="form-group mb-0">
            <button type="submit" class="btn btn-sm btn-danger">
                Delete
            </button>
        </div>
    </form>
@endif

resources/views/users/index.blade.php
@extends('layouts.app')
@section('content')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" />
    <link href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" defer></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <h1 class="lead">Table of users.</h1>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addNewUser">
        Add new user
    </button>
<!-- Register new user Form -->
    <div class="modal fade" id="addNewUser" tabindex="-1" role="dialog" aria-labelledby="addNewUserlLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Register a new User</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('users.store') }}" method="post">
                        @csrf
                        <div class="input-group mb-3">
                            <input type="text" name="first_name" id="first_name" class="form-control" placeholder="First name">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-user"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <input type="text" name="last_name" id="last_name" class="form-control" placeholder="Last name">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-user"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <input type="email" name="email" id="email" class="form-control" placeholder="Email">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <input type="password" name="password" id="password" class="form-control" placeholder="Password">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <input type="password" name="password_confirmation" id="password_confirmation" class="form-control" placeholder="Retype password">
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                        <div class="input-group mb-3">
                            <div class="col-4 pl-0">
                                <p class="text-center py-1">Select role:</p>
                            </div>
                            <select class="form-control col-8" name="role_id" id="role_id">
                                @foreach($roles as $id => $name)
                                    <option value="{{$id}}">{{$name}}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="row">
                            <div class="col-4">
                                <button type="submit" class="btn btn-primary btn-block">Register</button>
                            </div>
                            <!-- /.col -->
                        </div>
                    </form>
                </div>
                <!-- /.form-box -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
<!-- Edit user Form -->
    <div class="modal fade" id="editUser" tabindex="-1" role="dialog" aria-labelledby="editUserLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Edit a User</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="#" method="post" class="form" id="editUserForm">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <div class="input-group mb-3">
                                <span class="error alert alert-danger container-fluid" style="display: none"></span>
                                <input type="text" name="first_name" id="first_name_edit" class="form-control" placeholder="First name">
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-user"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="input-group mb-3">
                                <span class="error alert alert-danger container-fluid" style="display: none"></span>
                                <input type="text" name="last_name" id="last_name_edit" class="form-control" placeholder="Last name">
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-user"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="input-group mb-3">
                                <span class="error alert alert-danger container-fluid" style="display: none"></span>
                                <input type="email" name="email" id="email_edit" class="form-control" placeholder="Email">
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="input-group mb-3">
                                <span class="error alert alert-danger container-fluid" style="display: none"></span>
                                <input type="password" name="password" id="password_edit" class="form-control" placeholder="Password">
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-lock"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="input-group mb-3">
                                <input type="password" name="password_confirmation" id="password_confirmation_edit" class="form-control" placeholder="Password">
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-lock"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="input-group mb-3">
                                <div class="col-4 pl-0">
                                    <p class="text-center py-1">Select role:</p>
                                </div>
                                <select class="form-control col-8" name="role_id" id="role_id_edit">
                                    @foreach($roles as $id => $name)
                                        <option value="{{$id}}">{{$name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <input type="button" id="btn-save" data-user_id="#" class="btn btn-primary" value="Save" onclick="updateUser(this.dataset.user_id)">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    {{$dataTable->table()}}

@endsection

@push('scripts')
    {{$dataTable->scripts()}}

    <script type="text/javascript">
        function editUser(id){
            $.ajax({
                url: 'getData/'+ id,
                type: 'get',
                dataType: 'json',
                success: function(response) {
                    //Reset validation errors
                    $('#editUserForm input[name="first_name"]').parent().find('.error').hide();
                    $('#editUserForm input[name="last_name"]').parent().find('.error').hide();
                    $('#editUserForm input[name="email"]').parent().find('.error').hide();
                    $('#editUserForm input[name="password"]').parent().find('.error').hide();

                    var selector = $(jQuery('#editUser'));
                    selector.find('input[type="button"]').attr('data-user_id', response['data']['id']);
                    selector.find('input[name="first_name"]').val(response['data']['first_name']);
                    selector.find('input[name="last_name"]').val(response['data']['last_name']);
                    selector.find('input[name="email"]').val(response['data']['email']);
                    selector.find('select[id="role_id_edit"]').val(response['data']['role_id']);
                }});

            $('#editUser').modal('show');
        }
        function updateUser(id){
            $.ajax({
                url: 'users/' + id,
                method: 'PUT',
                data: $('#editUserForm').serializeArray(),
                success:function(){
                    alert("Success!");
                },
                error: function (xhr) {
                    //Reset validation errors
                    $('#editUserForm input[name="first_name"]').parent().find('.error').hide();
                    $('#editUserForm input[name="last_name"]').parent().find('.error').hide();
                    $('#editUserForm input[name="email"]').parent().find('.error').hide();
                    $('#editUserForm input[name="password"]').parent().find('.error').hide();

                    //Show validation errors
                    $.each(xhr.responseJSON.errors, function(key,value) {
                        $('#editUserForm input[name="'+key+'"]').parent().find('.error').text(value).show();
                    });
                },
            });
        }
    </script>
@endpush